let Name = "Naresh More";
let School = "Masai School";
let Grade = "A";
let Section = "Computer-A";
let Roll_no = 21;
let English, Math, Hindi;
English = 75;
Math = 80;
Hindi = 90;
Marks = English + Math + Hindi;
console.log("Name:",Name);
console.log("School:",School);
console.log("Grade:",Grade);
console.log("Section:",Section);
console.log("Roll No:",Roll_no);
console.log("English:",English);
console.log("Math:",Math);
console.log("Hindi:",Hindi);
console.log("Total Marks:",Marks);